# Generated by Django 2.1.1 on 2018-10-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('algorithm', models.CharField(choices=[('DH', 'DH'), ('DSA', 'DSA'), ('HMAC_MD5', 'HMAC-MD5'), ('HMAC_SHA1', 'HMAC-SHA1'), ('HMAC_SHA224', 'HMAC-SHA224'), ('HMAC_SHA256', 'HMAC-SHA256'), ('HMAC_SHA384', 'HMAC-SHA384'), ('HMAC_SHA512', 'HMAC-SHA512'), ('RSA', 'RSA'), ('RSAMD5', 'RSAMD5')], default='HMAC-SHA1', max_length=32)),
                ('passwd_len', models.IntegerField(default=512)),
                ('update_type', models.CharField(choices=[('HOST', 'HOST'), ('ZONE', 'ZONE')], default='HOST', max_length=16)),
                ('data', models.CharField(default='', max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=2048)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('ttl', models.IntegerField(default=3600)),
                ('rr_class', models.CharField(default='IN', max_length=64)),
                ('rr_type', models.CharField(default='A', max_length=16)),
                ('rr_data', models.CharField(max_length=256, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=2048)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('dns_port', models.IntegerField(default=53)),
                ('statistics_port', models.IntegerField(default=8053)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=2048)),
                ('default_transfer_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='dns_server.Key')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(default='_default', max_length=32)),
                ('zone_name', models.CharField(max_length=256, null=True)),
                ('zone_class', models.CharField(default='IN', max_length=256)),
                ('zone_serial', models.IntegerField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=2048)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='dns_server.Server')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='record',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='dns_server.Zone'),
        ),
    ]
