# Generated by Django 2.1.1 on 2018-10-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='algorithm',
            field=models.CharField(choices=[('HMAC-MD5.SIG-ALG.REG.INT', 'HMAC_MD5'), ('hmac-sha1', 'HMAC_SHA1'), ('hmac-sha224', 'HMAC_SHA224'), ('hmac-sha256', 'HMAC_SHA256'), ('hmac-sha384', 'HMAC_SHA384'), ('hmac-sha512', 'HMAC_SHA512')], default='hmac-sha1', max_length=32),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_serial',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
